### ISSUE TITLE
Use Case Test Cases

### ISSUE THREAD

**Issue by jaronfernandes** [jaronfernandes/InfoLingo#22]
Hardcoded tests for all our use-cases: Ranking, Grouping, Translation, Article Retrieval, and Summarisation.

**Comment by Jaiz183** [comment]
Progress update:
Completed interaction tests for summarisation and transfer article.

**Comment by jaronfernandes** [comment]
The tests I'll work on are Translation and Article Retrieval.

**Comment by jaronfernandes** [comment]
Completed translation and article retrieval tests.
