### ISSUE TITLE
Redirect Click on Article in HomeView to ArticleView

### ISSUE THREAD

**Issue by Jaiz183** [jaronfernandes/InfoLingo#41]
To finish up the app, clicking on an article in Home View should redirect the user to Article View. Otherwise, our app can only display one view in a single deployment.

**Comment by Jaiz183** [comment]
Made some progress with Jaron, but incomplete as of now.

**Comment by jaronfernandes** [comment]
Still needs to transfer the respective Article's data to ArticleView.

**Comment by Jaiz183** [comment]
Fixed this issue with Jaron in pull request #58.
